FROM ubuntu:22.04

RUN apt update && apt install tzdata -y
ENV TZ="Asia/Kolkata"
RUN apt install -y software-properties-common 
RUN apt install -y iptables 
RUN apt install -y curl 
RUN apt install -y iproute2 
RUN apt install -y ifupdown 
RUN apt install -y iputils-ping 
RUN apt install -y sudo  
RUN apt install -y wireguard
RUN apt install -y openssh-server 
RUN apt install -y net-tools 
RUN echo resolvconf resolvconf/linkify-resolvconf boolean false | debconf-set-selections 
RUN echo "REPORT_ABSENT_SYMLINK=no" >> /etc/default/resolvconf 
RUN apt install resolvconf
RUN echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
RUN add-apt-repository ppa:ondrej/php -y
RUN apt update && sudo apt upgrade -y
RUN apt install php8.1 libapache2-mod-php8.1 -y
RUN apt install php8.1-mysql -y
RUN apt install php8.1-mongodb -y
RUN apt install openssl -y 
RUN apt install php8.1-common -y
RUN apt install php8.1-curl -y
RUN apt install php8.1-mbstring -y
RUN apt install php8.1-xml -y
RUN apt install php8.1-zip -y
RUN apt install zip -y
RUN apt install unzip -y
RUN curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
RUN HASH=`curl -sS https://composer.github.io/installer.sig`
RUN php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN apt install apache2 -y
RUN apt install python3-pip -y 
RUN echo "www-data  ALL=NOPASSWD:ALL" | sudo tee /etc/sudoers.d/www-data
RUN apt install docker.io -y
RUN apt install certbot python3-certbot-apache -y
COPY ./docker-entrypoint.sh docker-entrypoint.sh
COPY ./000-default.conf /etc/apache2/sites-available/000-default.conf
COPY ./core /var/www/html
COPY ./systemd /root/systemd
COPY ./core_py /root/core_py
RUN a2enmod rewrite
RUN pip3 install psutil
RUN pip3 install pika
RUN chmod +x ./docker-entrypoint.sh

RUN sed -i -e 's/\r$//' ./docker-entrypoint.sh 

ENTRYPOINT [ "./docker-entrypoint.sh" ]



