FROM debian:11.3

RUN apt update -y
RUN apt install sudo -y
RUN sudo sh -c "echo 'deb http://deb.debian.org/debian buster-backports main contrib non-free' > /etc/apt/sources.list.d/buster-backports.list"
RUN apt update -y
RUN apt install wireguard -y
RUN apt install iptables curl iproute2 ifupdown iputils-ping wireguard openssh-server net-tools -y

RUN mkdir /var/run/sshd

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./docker-entrypoint.sh docker-entrypoint.sh

RUN chmod +x ./docker-entrypoint.sh

RUN sed -i -e 's/\r$//' ./docker-entrypoint.sh 

ENTRYPOINT [ "./docker-entrypoint.sh" ]